[package]
name = "exercise-html"
version = "0.1.0"
authors = ["Takashi Yoneuchi <takashi.yoneuchi@shift-js.info>"]
edition = "2018"

[[bin]]
name = "exercise-html"
test = false
bench = false

[dependencies]
thiserror = "1.0"
combine = "4.5.2"
